[package]
name = "du-rs"
version = "0.1.0"
authors = ["kautionb <kaution3@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
humansize = "1.1.0"